name: meshSettings
scale: 1.0
domain:
  minx: -3.0
  maxx: 8.0
  miny: -3.0
  maxy: 3.0
  minz: 0.0
  maxz: 5.0
  nx: 40
  ny: 20
  nz: 20
patches:
- name: inlet
  type: patch
  faces: [0, 4, 7, 3]
- name: outlet
  type: patch
  faces: [1, 5, 6, 2]
- name: front
  type: wall
  faces: [0, 1, 5, 4]
- name: back
  type: wall
  faces: [2, 3, 7, 6]
- name: bottom
  type: wall
  faces: [0, 1, 2, 3]
- name: top
  type: wall
  faces: [4, 5, 6, 7]

snappyHexSteps:
  castellatedMesh: true
  snap: true
  addLayers: true
geometry:
- name: ahmed.stl
  type: triSurfaceMesh
  refineMin: 1
  refineMax: 3
  featureEdges: true
  featureLevel: 3
  nLayers: 3
- name: box
  type: searchableBox
  min: [-0.5, -0.5, -0.5]
  max: [1, 1, 1]
castellatedMeshControls:
  maxLocalCells: 2000000
  maxGlobalCells: 5000000
  minRefinementCells: 5
  maxLoadUnbalance: 0.1
  nCellsBetweenLevels: 5
  features: []
  refinementSurfaces: []
  resolveFeatureAngle: 20
  refinementRegions: []
  locationInMesh:
  - 0
  - 0
  - 0
  allowFreeStandingZoneFaces: false
snapControls:
  nSmoothPatch: 3
  tolerance: 2.0
  nSolveIter: 100
  nRelaxIter: 8
  nFeatureSnapIter: 10
  implicitFeatureSnap: false
  explicitFeatureSnap: true
  multiRegionFeatureSnap: false
addLayersControls:
  relativeSizes: true
  expansionRatio: 1.2
  finalLayerThickness: 0.3
  minThickness: 0.001
  nGrow: 0
  featureAngle: 180
  nRelaxIter: 5
  nSmoothSurfaceNormals: 1
  nSmoothNormals: 3
  nSmoothThickness: 10
  maxFaceThicknessRatio: 0.5
  maxThicknessToMedialRatio: 0.3
  minMedianAxisAngle: 90
  nBufferCellsNoExtrude: 0
  nLayerIter: 10
meshQualityControls:
  maxNonOrtho: 75
  maxBoundarySkewness: 4
  maxInternalSkewness: 4
  maxConcave: 180
  minTetQuality: 1.0e-30
  minVol: 1.0e-30
  minArea: 1.0e-30
  minTwist: 0.001
  minDeterminant: 0.001
  minFaceWeight: 0.01
  minVolRatio: 0.01
  minTriangleTwist: -1
  nSmoothScale: 4
  errorReduction: 0.75
mergeTolerance: 1.0e-6
debug: 0
